# Generated by Django 2.2.13 on 2021-04-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('BL', 'Bronze Lootchest'), ('SL', 'Silver Lootchest'), ('GL', 'Gold Lootchest')], max_length=2),
        ),
    ]
